version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - dependabot
  ignore:
  - dependency-name: chai
    versions:
    - 4.3.2
  - dependency-name: "@kth/http-responses"
    versions:
    - 1.0.42
