version: '3'

services:
  web:
    build: .
    env_file: 
      - .env
    environment:
      PORT: 3000 # Starts Node on this port, if not set defaults to 80.
      PORTILLO_CLUSTER: "development" # Will show under /_monitor
      # APPINSIGHTS_INSTRUMENTATIONKEY: "aaaaaa-bbbbbb-cccccc-dddddd-eeeeee" # Add key to start collecting data in Application Insights.
    ports:
      - 3000:3000