version: '3'

services:

  #############################################
  # Start http://web:80/
  #############################################
  web:
    # if not --build and kth-azure-app already exists in
    # your local computers registry 'image' is used.
    image: $LOCAL_IMAGE_ID
    
    # Possible configuration for the app.
    environment:
      PORTILLO_CLUSTER: "active" # Will show under /_monitor
      DISABLE_REQUEST_LOGGING: "true"
      APPINSIGHTS_INSTRUMENTATIONKEY: ""
      APPLICATIONS_API_HOST: "api.kth.se"
      DOMAIN_OWNERSHIP_VERIFICATION_FILE: "alskjdfasd_verify_domain.html"
      DOMAIN_OWNERSHIP_VERIFICATION_FILE_CONTENT: google
    ports:
      - 80

      #############################################
  # Start the client running tests 
  # agains http://web:80/
  #############################################
  integration-tests:
    # Build client image and run tests
    # from inside that.
    build: ./tests/integration-tests
    environment:
      DOMAIN_OWNERSHIP_VERIFICATION_FILE: "alskjdfasd_verify_domain.html"
      DOMAIN_OWNERSHIP_VERIFICATION_FILE_CONTENT: "google"
